(source gnu)
(source melpa)
(source melpa-stable)

(depends-on "aggressive-indent")
(depends-on "chinese-fonts-setup")
(depends-on "chinese-pyim")
(depends-on "cmake-font-lock")
(depends-on "cmake-mode")
(depends-on "enh-ruby-mode")
(depends-on "go-mode")
(depends-on "inf-ruby")
(depends-on "robe")
(depends-on "web-mode")
